name: Generate thumbnails

on:
  push:
    branches: [ main ]
    paths:
      - 'ads/**.html'
      - '.github/workflows/thumbs.yml'
      - 'generateThumbs.js'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Generate thumbs & manifest
        run: npm run thumbs

      - name: Commit thumbnails
        uses: EndBug/add-and-commit@v9
        with:
          add: 'thumbs --force'
          message: 'auto: update thumbnails [skip ci]'
